# A useful case used for executing the practice at daily work every day.
# use makefile to make the compile and execute the target at one line.


# use make flags to make every time you make will get the result show one time rather than according to the latest codes. -B
MAKEFLAGS = -B
all: File.c
	gcc $< -o $@
	./$@ # After you have make and got the value. You can execute it.
